### ISSUE TITLE
Routes available in App

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#14]
If we check the Design (#2) we can note these routes:

## `home` or root (`/`)

- [x] Azordev/maps-project#42

![image](https://user-images.githubusercontent.com/36519478/134940301-4d4e5a01-9b38-49e9-ae3c-ba62b0b14dbb.png)

## `check`

- [x] #48

![image](https://user-images.githubusercontent.com/36519478/134832825-8f5f27ce-351e-45b7-956b-651fe3aa035b.png)

## `delivery/:id`

- [x] Azordev/maps-project#39 

![image](https://user-images.githubusercontent.com/36519478/135971354-dfcbba85-4e4d-471f-840b-252848c9f4a3.png)

# `chat/:id`

- [x] Azordev/maps-project#40

![image](https://user-images.githubusercontent.com/36519478/134835165-124f26ba-56bd-40ed-89b5-34b88917ff31.png)

Related issues
 
- Azordev/frontend-template#4
- Azordev/maps-project#34 

## `confirm/:id`

- [x] Azordev/maps-project#43

![image](https://user-images.githubusercontent.com/36519478/134838120-865d5e82-2c68-4caa-8c2e-52bfe0c2e24d.png)

## error 404 and error 5XX

- [x] #49

![image](https://user-images.githubusercontent.com/36519478/134840367-0f82f170-c5f0-4a98-ae3f-e553ab1e00c9.png)

- [ ] app error 5XX

TBD

Notice:
- Should include id and timestamp of error
- Should include developer/technical staff contact information
- Should have a link to Home or other TBD

## Checklist

- [x] Define the route links to access the views
- [x] A router package is added to manage routes
- [x] This package doesn't break the app
- [x] A user can change between routes using URL and using links
- [x] There is a fallback for a not found route
- [ ] There is a way to show errors 5xx
