### ISSUE TITLE
Update Experience View   

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#49]
### Explanation:
The change of styles in the experience view, in the confirmation you must change the font, the color, place a new image and styles in the rating stars, change the color of the button,organize the content of the view that looks good in different mobile resolutions, take into account spaces and margins in the design, change in experience receipt confirmation modal check icon and text with the same transparency color.
Available graphic resources and design in FIgma link.

### SCREENSHOTS
<img width="653" alt="image" src="https://user-images.githubusercontent.com/97471255/154148136-fdeb03ce-1d4d-4ae4-a8fb-eeb8229134f4.png">

### CHECKLIST

- [ ] Color change in experience title `#005D9D` bold popins font.
- [ ] Change the centered image.
- [ ] Change the color of button to with code `#005D9D`
- [ ] Transparency wallpaper for popup `#0000FF` opacity 17%.
- [ ] Add message in popup, confirmation.
- [ ] Font color `#3B3B3C` in regular style and green check color icon.

### REFERENCE
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=322%3A28
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task
