### ISSUE TITLE
Update Confirmation View

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#50]
### Explanation:
Change text styles of header styles, put back button image, change form styles, change text color, border and background in fields, add report button and change button color , confirm all this in the mobile view, a Figma design link is attached to download the missing resources,organize the content of the view that looks good in different mobile resolutions, take into account spaces and margins in the design.

### SCREENSHOTS
![view_report](https://user-images.githubusercontent.com/4030477/155558393-0f8a9d5a-b5d2-4f3e-9044-44bb3e2bf9b8.jpg)

### CHECKLIST 

- [ ] Change the color of the header `#56ACDE`.
- [ ] Change font type: bold popins and color size `#002740` according to the layout.
- [ ] Place button on the back top left according to the image in figma.
- [ ] Change text field size and color, background color `#C4C4C4` to 23%, border `#5F6769` to 1px, font uses regular popins, all fields to uppercase.
- [ ] Toggle button styles report color `#F74326` and confirm buttons `#005D9D` side by side centered relative to form.

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=420%3A58
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=522%3A28

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task
