### ISSUE TITLE
Review And Update The Chat View

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#51]
### Explanation:
Chat view header and footer styles will be changed, a back button will be placed, icons and colors will be changed in chat. 

### SCREENSHOTS
![Chat view](https://user-images.githubusercontent.com/4030477/155562344-c4d086cc-c338-4bcb-9136-6e55d3a33b46.png)

 
### CHECKLIST 

- [ ] Change the colors of the `#9DBDFD` header.
- [ ] Change user icon.
- [ ] Change text styles, username in header with bold popins font and text color `#003B62`
- [ ] Place back button according to the design image.
- [ ] Change ´delivery chat´ icon.
- [ ] Change the color of the footer `#9DBDFD`
- [ ] Change color of text field `#3B3B3C`
- [ ] Replace send icon.
### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=522%3A28

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task
