### ISSUE TITLE
Observe And Update The Input

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#52]
### Explanation:
Insert ticket view, change styles in header, add back button, fonts, text field and button styles, design attached link in figma to download missing resources.

### SCREESHOTS

![view_start](https://user-images.githubusercontent.com/4030477/155564890-e2b003cc-b022-4faf-8835-6937a401802e.jpg)

### CHECKLIST

- [ ] Change the background color of the header with rounded corners to the layout color `#9DBDFD`
- [ ] Place back button aligned to the top left according to design
- [ ]Change title and subtitle text styles in header type: regular and bold popups to appropriate color `#002740`
- [ ] Change title styles in popins bold uppercase font color `#005D9D`
- [ ] Change text field size and color, background color `#C4C4C4` to 23%, border `#5F6769` to 1px, font uses regular popins, all fields to uppercase.
- [ ] Change button color color `#005D9D` appears in medium caps.

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=619%3A102

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task

**Comment by arodriguezl9302** [comment]
This task is not yet implemented in the project, for this reason it is impossible to fulfill @Israel-Laguan @e-azocar @Katsu08

**Comment by heliomar-pena** [comment]
@arodriguezl9302 yes, you can work in it. The steps to get the view is:

1. Run the project in local
2. When you did it, the "Welcome" page will be displayed
3. Then you click on the unique button that is in this page, and appears a page requesting a ticket number.

This page that request a ticket number, is the page that we want change in this task. 

If you wanna see the page like the screenshot in the issue, then you should reduce the resolution for a mobile screen size, then you will have the page that we was mentioned, you just need change the colors and maybe fix some things to do the page looks like the design in mobile

**Comment by arodriguezl9302** [comment]
ok, thanks, I'll start working on this today
