### ISSUE TITLE
Check And Update Before Receiving Modal

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#58]
### Explanation:
Change of informative modal styles, change font size, alert icon, button color, and transparency background.
Graphic resources are available in the attached figma links below.

### SCREENSHOTS
<img width="283" alt="image" src="https://user-images.githubusercontent.com/97471255/154495098-7ce6862d-cf70-4aa0-aee8-eeab3baeaeac.png">

### CHECKLIST

- [ ] Change alert icon.
- [ ] Change of font and font sizes type: Poppins bold and regular according to design text color `#3B3B3C` 
- [ ] Transparency wallpaper for popup `#0000FF` opacity 17%.
- [ ] Change color and letter in button `#005D9D`

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=420%3A148
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=522%3A28

**Comment by ygamboalh** [comment]
I want to be assigned to this task.

**Comment by heliomar-pena** [comment]
I considered updating the E.E to 2 since I noticed that the task was not so easy
