### ISSUE TITLE
Define list of Shared or Base Components

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#7]
Some shared components I see are

## Button

- [x] Azordev/maps-project#22

![image](https://user-images.githubusercontent.com/36519478/134856338-96100ce7-93b8-4bc7-96c1-c90086f6c3c0.png)

## Image

- [x] Azordev/maps-project#23

![image](https://user-images.githubusercontent.com/36519478/134857031-db67f707-072c-4941-905a-e755dad5b94b.png)

## Text

- [x] Azordev/maps-project#29

Also text in buttons, inputs, chat and forms, we have

![image](https://user-images.githubusercontent.com/36519478/134857618-1a5b39a6-0ca9-4ff1-a549-52c4db960885.png)

## Input 

- [x] Azordev/maps-project#25

![image](https://user-images.githubusercontent.com/36519478/134858165-2631c4da-bf9b-4be6-9c59-8389f8c40a03.png)

## Forms

- [x] Azordev/maps-project#26

![image](https://user-images.githubusercontent.com/36519478/134858373-fb83f1d0-ad10-4a2d-b133-10171b6434e9.png)

## Modal

- [x] Azordev/maps-project#24

![image](https://user-images.githubusercontent.com/36519478/134858602-2161ce29-5d85-4f64-a23d-70a61e3bd9b2.png)

### Counter Time

- [x] Azordev/maps-project#27

![image](https://user-images.githubusercontent.com/36519478/134858839-b16e1592-fad7-429d-8a71-d2114e309e0b.png)

### Map y Markers

- [x] Azordev/maps-project#28

![image](https://user-images.githubusercontent.com/36519478/134859060-3b84c0c5-e63c-4247-8b06-d9610b8495b5.png)

### Rating

- [x] Azordev/maps-project#30

![image](https://user-images.githubusercontent.com/36519478/134859117-abb2e5c4-b5ad-4ed1-8333-e93c20b7d2d4.png)

### Chat and Chat Rows

- [x] Azordev/frontend-template#4

![image](https://user-images.githubusercontent.com/36519478/134859170-6615dcbf-70d3-458c-924e-7e347c97989f.png)

--- 

Did I miss something?
